export const appContainer = document.querySelector(".app-container");
export const dateArea = document.querySelector(".date");
export const countryArea = document.querySelector(".country p");
export const weatherImage = document.querySelector(".weather-img");
export const weatherTemp = document.querySelector(".weather-temp p");
export const weatherForecast = document.querySelector(".weather-forecast p");
export const maxTemp = document.querySelector(".max-temp p");
export const minTemp = document.querySelector(".min-temp p");
export const wind = document.querySelector(".wind p");
